@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("v1.0", $borderColor="#d73027")
AddElementTag("v1.1", $fontColor="#ffffff")
AddElementTag("backup", $fontColor="orange")

AddRelTag("backup", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())
AddRelTag("request", $textColor="blue", $lineColor="blue", $lineStyle = SolidLine())

Person(User, "Front", "")
Container(PartnerSystem, "Внешняя система партнера")

System_Boundary("OuterSystem", "Система автоматизации магазина стройматериалов") {

    Container(APIGateway, "APIGateway", "API управления ")

    System_Boundary("Users", "Домен пользовательского управления") {
        Container(Admin, "Микросервис авторизации/аутенфикации", "Проверяет и предоставляет доступ к системе")
        ContainerDb(UsersDb, "База данных пользователей")
        Rel_D(Admin, UsersDb, "Read/Write", "Ищет пользователей в БД и устанавливает их права")
    }
    System_Boundary("Products", "Домен товаров") {
        Container(catalog, "Микросервис управления журналом товаров", "Управление записями о товарах")
        Container(productSearch, "Микросервис навигации по складу", "Поиск местоположения товара на складе и актуализация информации об этом")
        Rel(productSearch, catalog, "Запрашивает данные о товаре")
        ContainerDb(ProductionDB, "БД товаров на складе")
        Rel(catalog, ProductionDB, "Read/Write", "Запрос информации по товарам в наличии на складе. Актуализация данных о товарах")
        Container(barcodeserv, "Микросервис генерации штрих-кодов", "Генерирует штрих-коды для товаров")
        Rel(productSearch, barcodeserv, "Запрос на генерацию штрих-кода")
        Rel(productSearch, ProductionDB, "")
    }

    System_Boundary("Documents", "Домен документооборота") {
        Container(docgenerating, "Микросервис генерации pdf документов", "Формирует документацию о товарах в печатном формате")
        Container(docvalidation, "Микросервис обработки документации", "Осуществляет проверку документации соответствию правилам")
        ContainerDb(docDb, "БД Документов")
        Rel(docgenerating, docDb, "Read", "Забирает данные для генерации докуменнта в печатном виде")
        Rel(docvalidation, docDb, "Read", "Проверка записи на соответствие правилам")
        Rel(docvalidation, docgenerating, "Запрос на формирование печатного документа")
    }

    System_Boundary("Finances", "Домен управления сделками") {
        Container(accounting, "Микросервис финансовых операций", "Ведет учет закупок и продаж товаров")
        ContainerDb(accountingDb, "БД закупок и продаж", "")
        Rel(accounting, accountingDb, "Read/Write", "Фиксирует операции в БД")
    }

    System_Boundary("Delivery", "Домен доставки") {
        Container(deliverySys, "Микросервис управления доставками", "Формирует поручение на доставку")
        ContainerDb(deliveryDb, "БД заявок на доставку", "Хранит записи о текущих доставках")
        Rel(deliverySys, deliveryDb, "Read/Write", "Фиксирует новые заявки в БД, обновляет статус заявок и удаляет неактуальные заявки")
    }

    System_Boundary("Orders", "Домен заказов") {
        Container(OrdersSys, "Микросервис управления заказами", "Создает, удаляет и изменяет заявки на заказ")
        ContainerDb(OrdersDb, "БД заказов", "Ведение журнала заказов")
        Rel(OrdersSys, OrdersDb, "Read/Write", "Создает запись о заявке, актуализирует данные записи о заявке, удаляет неактуальные заявки")
    }
  

    System_Boundary("Partners", "Домен внешних взаимодействий") {
        Container(communication, "Микросервис взаимодействия с внешними системами", "Запрашивает информацию со складов партнеров и формирует поручение на партнерскую доставку")
        ContainerDb(communicationDb, "БД записей ответов внешних систем. Шард 1", "shard1", "Записи о наличии товара на складе партнера")
        ContainerDb(communicationDb1, "БД записей ответов внешних систем. Шард 2", "shard2", "Записи о партнерских доставках")
        Rel(communication, communicationDb, "Read/Write")
        Rel(communication, communicationDb1, "Read/Write")
    }

    Container(cash, "Reddis", "КЭШ")
}

Rel_L(APIGateway, cash, "кэширование запросов")

Rel(accounting, docvalidation, "")
Rel(productSearch, docvalidation, "")
Rel(OrdersSys, productSearch, "Запрос проверки наличия товара")
Rel(OrdersSys, communication, "Запрос проверки наличия товара")

Rel_D(User, APIGateway, "Взаимодействие с системой")
Rel_D(APIGateway, Admin, "Авторизация")


Rel_U(communication, PartnerSystem, "")



SHOW_LEGEND()
@enduml