@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("v1.0", $borderColor="#061038", $fontColor="#ffffff")
AddElementTag("v1.1", $fontColor="#ffffff")
AddElementTag("backup", $fontColor="orange")

AddRelTag("backup", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())
AddRelTag("request", $textColor="blue", $lineColor="blue", $lineStyle = SolidLine())

Person(User, "Пользователь", "Сотрудник нашей компании", $tags="v1.0")

System_Boundary(s1, "Система нашей компании"){

Container(MicroServ, "Микросервис авторизации/аутенфикации", $tags="v1.0")
Container(MicroServ1, "Микросервис приемки товара", "Формирует акты приема и вносит записи в БД", $tags="v1.0")
Container(MicroServ2, "Микросервис проверки сертификатов", "Проверяет наличие документов на товар и соответствие их требованиям", $tags="v1.0")
Container(MicroServ3, "Микросервис формирования pdf документов", "Формирует pdf документы и позволяет выгружать их на локальный диск", $tags="v1.0")
Container(MicroServ4, "Микросервис отслеживания", "Отслеживает местонахождение товара на складе (номер стеллажа) и актуализирует информацию о местонахождении товара", $tags="v1.0")
Container(MicroServ5, "Микросервис генерации штрихкодов", "Генерирует штрихкоды", $tags="v1.0")
Container(MicroServ6, "Микросервис запроса и получения информации у партнеров", "Запрашивает информацию о наличии товара на складе партнера и приема информации о поступлении/ликвидации товара на складе поставщика", $tags="v1.0")
Container(MicroServ7, "Микросервис доставки", "формирует и обрабатывает заявки на доставку", $tags="v1.0")
Container(MicroServ8, "Микросервис формирования документов на доставку", "Формирует необходимые документы", $tags="v1.0")
Container(MicroServ9, "Микросервис отгрузки", "Формирование форм для отгрузки товаров и изменение/удаление записей в БД", $tags="v1.0")
ContainerDb(db, "База данных", "SQL", "БД товаров и заказов")

Rel(MicroServ4, db, "Read/Write", "Сверяет информацию", $tags="")
Rel(MicroServ5, db, "Read/Write", "Присваивает товару код", $tags="")
}

System_Boundary(s2, "Система компании-партнера"){
}

SHOW_LEGEND()
@enduml