@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("v1.0", $borderColor="#d73027")
AddElementTag("v1.1", $fontColor="#ffffff")
AddElementTag("backup", $fontColor="orange")

AddRelTag("backup", $textColor="orange", $lineColor="orange", $lineStyle = DashedLine())
AddRelTag("request", $textColor="blue", $lineColor="blue", $lineStyle = SolidLine())


System_Boundary("OuterSystem", "Система автоматизации магазина стройматериалов") {


    System_Boundary("Products", "Домен товаров") {
        Container(catalog, "Система учета товара", "Управление записями о товарах")
        Container(productSearch, "Система поиска товара", "Поиск местоположения товара на складе и актуализация информации об этом")
        Rel(productSearch, catalog, "Запрашивает данные о товаре")
    }

    System_Boundary("Documents", "Домен документооборота") {
        Container(docgenerating, "Система формирования документации", "Формирует документацию о товарах в печатном формате")
        Container(docvalidation, "Система проверки документации", "Осуществляет проверку документации соответствию правилам")
    }

    System_Boundary("Finances", "Домен управления денежным оборотом") {
        Container(accounting, "Система учета операций", "Ведет учет закупок и продаж товаров")
    }

    System_Boundary("Delivery", "Домен доставки") {
        Container(deliverySys, "Система управления доставкой", "Формирует поручение на доставку")
    }

    System_Boundary("Users", "Домен пользовательского управления") {
        Container(Admin, "Система пользовательского управления", "Управляет учетными записями")
    }

    System_Boundary("Orders", "Домен заказов") {
        Container(OrdersSys, "Система управления заказами", "Обрабатывает заявки на заказ")
    }
  

    System_Boundary("Partners", "Домен внешних взаимодействий") {
        Container(communication, "Система партнерских сделок", "Запрашивает информацию со складов партнеров и формирует поручение на партнерскую доставку")
    }

}

SHOW_LEGEND()
@enduml