= ER модель "РБД системы магазина"

== Описание
=== Сущность "Product"
  Содержит в себе информацию о товаре
  .Структура
  [cols="1,1,1,1", hrows=1]
  |====
  .1+|Атрибут
  1+|Название
  1+|Обязательность
  1+|Описание

  | id
  | уникальный идентификатор
  | да
  |====

     id - уникальный идентификатор
     Product_name - Наименование товара
     creation_date - Дата создания записи
     changed_date - Дата последнего изменения записи
     amount - кол-во на складах
     category - категория товаров

=== Сущность "Order"
    Содержит в себе информацию о заказе

=== Сущность "User_employee"
    Содержит в себе информацию о сотруднике

=== Сущность "User_client"
    Содержит в себе информацию о покупателе

=== Сущность "OurStorage"
    Содержит в себе информацию о складе нашей компании

=== Сущность "PartnerStorage"
    Содержит в себе информацию о складе компании-партнера

=== Сущность "Delivery"
    Содержит в себе информацию о доставляемом заказе

=== Сущность "EmployeeOrders"
    Сущность, связывающая заказ с оформившим его сотрудником