= Kafka

== Брокер обработки Событий заказов

* Название:  order.events
* Для чего: Хранит сообщения о событиях связанных с заказом (создание, редактирование, смена статуса, деактивация)

=== Топик order.creation  - создание новой записи о заказе
* *Producer*: OrderSys (микросервис управления заказами)
* *Consumers*: 
** productSearch (микросервис поиска товаров по складу)
** communication (микросервис внешних взаимодействий)
* *Гарантии доставки*
- acks = all
- enable.idempotents = true
- manual.commit
* Кол-во партиций - 2

* *Примеры сообщений:*

*JSON*

[source, json]
----
{
  "key": order.creation,
  "value": "",
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "exampleId"
    },
    "number": 1233456789,
    "creation_date": DD-MM-YYYY 00:00:00,
    "changing_date": DD-MM-YYYY 00:00:00,
    "cost": 1.00,
    "Employee": {
      "$oid": "exampleId"
    },
    "Client": {
     "$oid": "exampleId"
    },
    "Product_id": ["123456789", "113456789", "111456789"]
}]
}
----
*Avro*
[source, avro]
----
{
  "namespace": "avro",
  "type": "record",
  "name": "NewOrder",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "number",
      "type": "long"
    },
    { "name": "creation_date",
      "type": "date"
    },
    { "name": "changing_date",
      "type": "date"
    },
    { "name": "cost",
      "type": "decimal"
    },
    {
      "name": "employee",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "position", "type": "string"}
      ]
    },
    {
      "name": "client",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "userrank", "type": "string"}
      ]
    },
    {
      "name": "Product_id",
      "type": "array"
    }
  ]
}
----

== Топик order.update - обновление информации в существующем заказе, изменение статуса заказа
* *Producer*: 
 - OrderSys (микросервис управления заказами)
* *Consumers*:
 - accountingSys (микросервис финансовых операций)
 - deliveryDys (микросервис доставок)
* Кол-во партиций 
* Гарантии доставки
- acks = all
- enable.idempotents = false
- manual.commit

* Примеры сообщений:

*JSON*

[source, json]
----
{
  "key": order.update,
  "value": {
    "number": "int",
    "cost": 1.00,
    "Employee": {
      "$oid": "exampleId"
    },
    "Client": {
     "$oid": "exampleId"
    },
    "Product_id": ["123456789", "113456789", "111456789"]
  },
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "exampleId"
    },
    "creation_date": DD-MM-YYYY 00:00:00,
    "changing_date": DD-MM-YYYY 00:00:00,
}]
}
----

*Avro*

[source,avro]
----
{
  "namespace": "avro",
  "type": "record",
  "name": "UpdateOrder",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "number",
      "type": "long"
    },
    { "name": "creation_date",
      "type": "date"
    },
    { "name": "changing_date",
      "type": "date"
    },
    { "name": "cost",
      "type": "decimal"
    },
    {
      "name": "employee",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "position", "type": "string"}
      ]
    },
    {
      "name": "client",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "userrank", "type": "string"}
      ]
    },
    {
      "name": "Product_id",
      "type": "array"
    }
  ]
}
----


== Топик order.deactivate - деактивация записи о заказе, помещение записи в архив
* *Producer*: OrderSys (микросервис управления заказами)
* *Consumers*:
- acks = all
- enable.idempotents
- manual.commit

* Примеры сообщений

*JSON*

[source,json]
----
{
  "key": order.deactivation,
  "value": {
    "number": 1233456789,
    "creation_date": DD-MM-YYYY 00:00:00,
    "changing_date": DD-MM-YYYY 00:00:00,
    "status": deactivate
    "Employee": {
      "$oid": "exampleId"
    },
    "Client": {
     "$oid": "exampleId"
    },
    "adress": "string"
    },
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "exampleId"
    }
}]
}
----

*Avro*

[source,avro]
----
{
  "namespace": "avro",
  "type": "record",
  "name": "deactivateOrder",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "number",
      "type": "long"
    },
    { "name": "creation_date",
      "type": "date"
    },
    { "name": "changing_date",
      "type": "date"
    },
    { "name": "status",
      "type": "enum"
    },
    {
      "name": "employee",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "position", "type": "string"}
      ]
    },
    {
      "name": "client",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "userrank", "type": "string"}
      ]
    }
    {
      "name": "adress",
      "type": "string"
    }
  ]
}
----


 
== Брокер Доставок
* Название:  delivery.events
* Для чего: Хранит сообщения о событиях связанных с доставкой (создание новой доставки, изменение статуса, архивация записи о завершенной доставке)
=== Топик delivery.creation
* *Producer*: deliverySys
* *Consumers*: OrderSys
* Колличество партиций
* Гарантии доставки
  - а

* Примеры сообщений

*JSON*

[source,json]
----
{
  "key": delivery.creation,
  "value": {
    "number": "int",
    "creation_date": DD-MM-YYYY 00:00:00,
    "changing_date": DD-MM-YYYY 00:00:00,
    "cost": 1.00,
    "Employee": {
      "$oid": "exampleId"
    },
    "Client": {
     "$oid": "exampleId"
    },
    "adress": "string",
    "storage_id": "exampleId",
    "Product_id": ["123456789", "113456789", "111456789"]
    },
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "exampleId"
    }
}]
}
----

*Avro*

[source,avro]
----
{
  "namespace": "avro",
  "type": "record",
  "name": "NewOrder",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "number",
      "type": "long"
    },
    { "name": "creation_date",
      "type": "date"
    },
    { "name": "changing_date",
      "type": "date"
    },
    { "name": "cost",
      "type": "decimal"
    },
    {
      "name": "employee",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "position", "type": "string"}
      ]
    },
    {
      "name": "client",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "userrank", "type": "string"}
      ]
    },
    {
      "name": "adress",
      "type": "string"
    },
    {
      "name": "Product_id",
      "type": "array"
    }
  ]
}
----


=== Топик delivery.update
* *Producer*: deliverySys
* *Consumers*: OrderSys
* Колличество партиций
* Гарантии доставки
  - а

* Примеры сообщений:

*JSON*

[source, json]
----
{
  "key": delivery.update,
  "value": {
    "number": 1233456789,
    "creation_date": DD-MM-YYYY 00:00:00,
    "changing_date": DD-MM-YYYY 00:00:00,
    "order_status": inprocess,
    "Employee": {
      "$oid": "exampleId"
    },
    "Client": {
     "$oid": "exampleId"
    },
    "adress": "string",
    "Product_id": ["123456789", "113456789", "111456789"]
    },
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "exampleId"
    }
}]
}
----

*Avro*

[source,avro]
----
{
  "namespace": "avro",
  "type": "record",
  "name": "UpdateDelivery",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "number",
      "type": "long"
    },
    {
      "name": "status",
      "type": "enum"
    }
    { "name": "creation_date",
      "type": "date"
    },
    { "name": "changing_date",
      "type": "date"
    },
    { "name": "cost",
      "type": "decimal"
    },
    {
      "name": "employee",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "position", "type": "string"}
      ]
    },
    {
      "name": "client",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "userrank", "type": "string"}
      ]
    },
    {
      "name": "adress",
      "type": "string"
    },
    {
      "name": "Product",
      "type": "array"
    }
  ]
}
----


=== Топик delivery.archivate
* *Producer*: deliverySys
* *Consumers*: OrderSys
* Колличество партиций
* Гарантии доставки
  - а

* Примеры сообщений:

*JSON*

[source,json]
----
{
  "key": delivery.archivation,
  "value": {
    "number": "int",
    "creation_date": DD-MM-YYYY 00:00:00,
    "changing_date": DD-MM-YYYY 00:00:00,
    "status": archivated,
    "Employee": {
      "$oid": "exampleId"
    },
    "Client": {
     "$oid": "exampleId"
    },
    "Product_id": ["123456789", "113456789", "111456789"]
    },
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "exampleId"
    }
}]
}
----

*Avro*

[source,avro]
----
{
  "namespace": "avro",
  "type": "record",
  "name": "delivery.archivation",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "number",
      "type": "long"
    },
    { "name": "creation_date",
      "type": "date"
    },
    { "name": "changing_date",
      "type": "date"
    },
    { "name": "status",
      "type": "enum"
    },
    {
      "name": "employee",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "position", "type": "string"}
      ]
    },
    {
      "name": "client",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "userrank", "type": "string"}
      ]
    },
    {
      "name": "Product_id",
      "type": "array"
    }
  ]
}
----


== Брокер Финансовых операций
* *Producer*: deliverySys
* *Consumers*: OrderSys
* Колличество партиций
* Гарантии доставки
  - а

=== Топик Новая запись о финансовой операции
* Примеры сообщений

*JSON*

[source,json]
----
{
  "key": delivery.creation,
  "value": {
    "creation_date": DD-MM-YYYY 00:00:00,
    "order_id": {
      "$oid": "exampleId"
    },
    "Employee": {
      "$oid": "exampleId"
    },
    "Client": {
     "$oid": "exampleId"
    },
    "operation_type": purchase,
    "total": 100.00,
    "Products": [{
      "Product_id": "exampleId",
      "cost": 1.00,
      "amount": 100,
      "storage_id": "exampleId",
    }]
    },
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "exampleId"
    }
  }]
}
----

*Avro*

[source,avro]
----
{
  "namespace": "avro",
  "type": "record",
  "name": "NewOrder",
  "fields": [
    {
      "name": "id",
      "type": "integer"
    },
    {
      "name": "creation_date",
      "type": "date"
    },
    {
      "name": "Employee",
      "type": "record",
      "fields": [
        {"name": "user_id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "position", "type": "string"}
      ]
    },
    {
      "name": "Client",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "userrank", "type": "string"}
      ]
    },
    {
      "name": "operation_type",
      "type": "enum"
    },
    {
      "name": "total",
      "type": "decimal"
    },
    {
      "name": "Products",
      "type": "record",
      "fields":
        {"name": "Product_id", "type": "string"},
        {"name": "cost", "type": "decimal"},
        {"name": "amount", "type": "string"},
        {"name": "storage_id", "type": "string"}
    }
  ]
}
----


== Брокер Документооборота
* Название:  documents
* Для чего: Хранит сообщения о запросе документации на товар

=== Топик запроса на документацию о товаре
* *Producer*: deliverySys
* *Consumers*:
** docvalidationSys
* *Гарантии доставки*
- acks = 0
- enable.idempotents = true
- manual.commit
* Примеры сообщений:

*JSON*

[source,json]
----

----

*Avro*

[source,avro]
----

----

