= Kafka

== Брокер обработки Событий заказов

* Название:  order.events
* Для чего: Хранит сообщения о событиях связанных с заказом (создание, редактирование, смена статуса, деактивация)

=== Топик order.creation  - создание новой записи о заказе
* *Producer*: OrderSys (микросервис управления заказами)
* *Consumers*: 
** productSearch (микросервис поиска товаров по складу)
** communication (микросервис внешних взаимодействий)
* *Гарантии доставки*
- acks = 1
- enable.idempotents = true
- manual.commit
* Кол-во партиций - 2

* *Примеры сообщений:*

*JSON*

[source, json]
----
{
  "key": order.creation,
  "value": "",
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "67a9aed1137279e67df8780f"
    },
    "number": "int",
    "creation_date": "dateTime",
    "cost": "Decimal",
    "Employee": {
      "$oid": "67a330ca1434847c6979bb30"
    },
    "Client": {
     "$oid": "67a335561434847c6979bb31"
    },
    "Product_id": array
}]
}
----
*Avro*
[source, avro]
----
{
  "namespace": "avro",
  "type": "record",
  "name": "NewOrder",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "number",
      "type": "long"
    },
    { "name": "creation_date",
      "type": "date"
    },
    { "name": "cost",
      "type": "decimal"
    }
    {
      "name": "employee",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "position", "type": "string"}
      ]
    }
    {
      "name": "Product",
      "type": "array"
    }
  ]
}
----

== Топик order.update - обновление информации в существующем заказе, изменение статуса заказа
* *Producer*: 
 - OrderSys (микросервис управления заказами)
* *Consumers*:
 - accountingSys (микросервис финансовых операций)
 - deliveryDys (микросервис доставок)
* Кол-во партиций 
* Гарантии доставки
- acks = all
- manual.commit

* Примеры сообщений:

*JSON*

[source, json]
----
{
  "key": order.creation,
  "value": "",
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "67a9aed1137279e67df8780f"
    },
    "number": "int",
    "creation_date": "dateTime",
    "cost": "Decimal",
    "Employee": {
      "$oid": "67a330ca1434847c6979bb30"
    },
    "Client": {
     "$oid": "67a335561434847c6979bb31"
    },
    "Product_id": array
}]
}
----

*Avro*

[source,avro]
----
{
  "namespace": "avro",
  "type": "record",
  "name": "UpdateOrder",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "number",
      "type": "long"
    },
    { "name": "creation_date",
      "type": "date"
    },
    { "name": "changing_date",
      "type": "date"
    },
    { "name": "cost",
      "type": "decimal"
    }
    {
      "name": "employee",
      "type": "record",
      "fields": [
        {"name": "id", "type": "long"},
        {"name": "name", "type": "string"},
        {"name": "position", "type": "string"}
      ]
    }
    {
      "name": "Product",
      "type": "array"
    }
  ]
}
----


== Топик order.deactivate - деактивация записи о заказе, помещение записи в архив
* *Producer*: OrderSys (микросервис управления заказами)
* *Consumers*:
- acks = all
- enable.idempotents
- manual.commit

* Примеры сообщений

*JSON*

[source,json]
----

----

*Avro*

[source,avro]
----

----


 
== Брокер Доставок
* Название:  delivery.events
* Для чего: Хранит сообщения о событиях связанных с доставкой (создание новой доставки, изменение статуса, архивация записи о завершенной доставке)
=== Топик delivery.creation
* *Producer*: deliverySys
* *Consumers*: OrderSys
* Колличество партиций
* Гарантии доставки
  - а

* Примеры сообщений

*JSON*

[source,json]
----

----

*Avro*

[source,avro]
----

----


=== Топик delivery.update
* *Producer*: deliverySys
* *Consumers*: OrderSys
* Колличество партиций
* Гарантии доставки
  - а

=== Топик delivery.archivate
* *Producer*: deliverySys
* *Consumers*: OrderSys
* Колличество партиций
* Гарантии доставки
  - а

* Примеры сообщений:

*JSON*

[source,json]
----

----

*Avro*

[source,avro]
----

----


== Брокер Финансовых операций
* *Producer*: deliverySys
* *Consumers*: OrderSys
* Колличество партиций
* Гарантии доставки
  - а

=== Топик о новой финансовой операции
* Примеры сообщений

*JSON*

[source,json]
----

----

*Avro*

[source,avro]
----

----


=== Топик 

=== Топик 
* Примеры сообщений:

*JSON*

[source,json]
----

----

*Avro*

[source,avro]
----

----


== Брокер Документооборота
* Название:  documents
* Для чего: Хранит сообщения о
* Примеры сообщений:

*JSON*

[source,json]
----

----

*Avro*

[source,avro]
----

----

