= Kafka

== Топики

=== Топик Событий заказов
* Название:  order.events
* Для чего: Хранит сообщения о событиях связанных с заказом (создание, редактирование, смена статуса, деактивация)
* События:
** order.creation - создание новой записи о заказе
** order.update - обновление информации в существующем заказе, изменение статуса заказа
** order.deactivate - деактивация записи о заказе, помещение записи в архив 
* Producer: OrderSys (микросервис управления заказами)
* Subscribers: 
** productSearch (микросервис поиска товаров по складу)
** communication (микросервис внешних взаимодействий)
** deliverySys (микросервис управления доставками)
* Примеры сообщений:

*JSON*
[source, json]
----
{
  "key": order.creation,
  "value": "",
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "67a9aed1137279e67df8780f"
    },
    "number": "int",
    "creation_date": "dateTime",
    "cost": "Decimal",
    "Employee": {
      "$oid": "67a330ca1434847c6979bb30"
    },
    "Client": {
     "$oid": "67a335561434847c6979bb31"
    },
    "Delivery": {
     "creation_date": "datetime",
      "delivery_service": "String",
      "adress": "String",
     "cost": "decimal"
    },
    "Product_id": array
}]
}
----
*Avro*
[source, avro]
----
{}
----
 
=== Топик Доставок
* Название:  delivery.events
* Для чего: Хранит сообщения о событиях связанных с доставкой (создание новой доставки, изменение статуса, архивация записи о завершенной доставке)
* Примеры сообщений:

*JSON*


=== Топик Финансовых операций
* Название:  Accounting
* Для чего: Хранит сообщения о
* Примеры сообщений:

*JSON*


=== Топик Документооборота
* Название:  documents
* Для чего: Хранит сообщения о
* Примеры сообщений:

*JSON*

