= Kafka

== Брокер обработки Событий заказов

* Название:  order.events
* Для чего: Хранит сообщения о событиях связанных с заказом (создание, редактирование, смена статуса, деактивация)

=== Топик order.creation  - создание новой записи о заказе
* *Producer*: OrderSys (микросервис управления заказами)
* *Consumers*: 
** productSearch (микросервис поиска товаров по складу)
** communication (микросервис внешних взаимодействий)
* *Гарантии доставки*
- acks = 1
- enable.idempotents = true
- manual.commit
* Кол-во партиций - 2

* *Примеры сообщений:*

*JSON*

[source, json]
----
{
  "key": order.creation,
  "value": "",
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "67a9aed1137279e67df8780f"
    },
    "number": "int",
    "creation_date": "dateTime",
    "cost": "Decimal",
    "Employee": {
      "$oid": "67a330ca1434847c6979bb30"
    },
    "Client": {
     "$oid": "67a335561434847c6979bb31"
    },
    "Product_id": array
}]
}
----
*Avro*
[source, avro]
----
{}
----

== Топик order.update - обновление информации в существующем заказе, изменение статуса заказа
* *Producer*: 
 - OrderSys (микросервис управления заказами)
* *Consumers*:
 - accountingSys (микросервис финансовых операций)
 - deliveryDys (микросервис доставок)
* Кол-во партиций 
* Гарантии доставки
- acks = all
- manual.commit

* Примеры сообщений:

*JSON*

[source, json]
----
{
  "key": order.creation,
  "value": "",
  "timestamp": DD-MM-YYYY 00:00:00,
  "headers": [{
    "_id": {
      "$oid": "67a9aed1137279e67df8780f"
    },
    "number": "int",
    "creation_date": "dateTime",
    "cost": "Decimal",
    "Employee": {
      "$oid": "67a330ca1434847c6979bb30"
    },
    "Client": {
     "$oid": "67a335561434847c6979bb31"
    },
    "Product_id": array
}]
}
----

== Топик order.deactivate - деактивация записи о заказе, помещение записи в архив
* *Producer*: OrderSys (микросервис управления заказами)
* *Consumers*:
- acks = all
- enable.idempotents
- manual.commit

 
== Брокер Доставок
* Название:  delivery.events
* Для чего: Хранит сообщения о событиях связанных с доставкой (создание новой доставки, изменение статуса, архивация записи о завершенной доставке)
=== Топик delivery.creation

=== Топик delivery.update

=== Топик delivery.archivate
* Примеры сообщений:

*JSON*


== Брокер Финансовых операций
* Название:  Accounting
* Для чего: Хранит сообщения о

=== Топик о новой финансовой операции

=== Топик 

=== Топик 
* Примеры сообщений:

*JSON*


== Брокер Документооборота
* Название:  documents
* Для чего: Хранит сообщения о
* Примеры сообщений:

*JSON*

